defaults: &defaults
  twitter:
    hashtag: TeamSpark
    text: Donate to Spark of Love to get a free Verismo latte. Find a @starbucks store near you http://givethruyeti.com
  donation:
    number: 80100
    body: ABC7
  maps:
    key: AIzaSyBENRZVAXcgbYid8376aTCyxa87gF2ZNjQ

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  maps:
    key: AIzaSyAHYUT0AlR_540CT87nFPg5YEIM8bzzrV4